spring:
  kafka:
    bootstrap-servers: 'kafka-broker-1-1:9092,kafka-broker-2-1:9092,kafka-broker-3-1:9092'
    input-topic: 'location-update'
  spring:
    json:
      trusted:
        packages: 'com.hpwv.*'
